server:
  port: 80

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://47.94.138.137:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: qyk
    password: qyk